# Generated by Django 4.2.16 on 2025-09-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0115_alter_venda_options'),
        ('estoque', '0033_auto_numero_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueimei',
            name='loja_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imei_vendidos', to='vendas.loja', verbose_name='Loja da Venda'),
        ),
    ]
