# Generated by Django 4.2.16 on 2025-09-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_estoqueimei_loja_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueimei',
            name='loja_venda',
        ),
    ]
