services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static
      - ./mediafiles:/app/mediafiles
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8010 core.asgi:application"
    restart: always
    ports:
      - '8010:8010'
    networks:
      - mynetwork

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6385:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
