version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static
      - ./mediafiles:/app/mediafiles
    command: 'sh -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn -c ./configs/configs.py core.wsgi"'
    restart: always
    ports:
      - '8033:8033'
    networks:
      - mynetwork

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
