version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./static:/app/static
      - ./mediafiles:/app/mediafiles
    command: >
      sh -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8010 core.asgi:application
      "
    restart: always
    ports:
      - '8010:8010'
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
