# Generated by Django 4.2.17 on 2026-04-02 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_sessions/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Sessão de Foto',
                'verbose_name_plural': 'Sessões de Foto',
            },
        ),
    ]
