# Generated by Django 4.2.16 on 2025-07-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0109_alter_contato_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0018_produto_valor_8_vezes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('valor_repasse_logista', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entrada_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_8_vezes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_6_vezes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_4_vezes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
