# Generated by Django 4.2.16 on 2025-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_produto_valor_8_vezes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_10_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
