# Generated by Django 4.2.16 on 2025-11-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produto_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo'], 'permissions': (('view_all_produtos', 'Can view all produtos'),), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
