# Generated by Django 4.2.16 on 2026-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_iphone',
            field=models.BooleanField(default=False, verbose_name='É iPhone?'),
        ),
    ]
