# Generated by Django 4.2.16 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_produto_is_iphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_12_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_14_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
