# Generated by Django 4.2.17 on 2026-02-21 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0136_parcelamento_produto_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0023_produto_valor_12_vezes_valor_14_vezes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor base (iPhone)'),
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('qtd_vezes', models.IntegerField(unique=True, verbose_name='Quantidade de vezes')),
                ('porcentagem_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de juros (%)')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
                'ordering': ['qtd_vezes'],
            },
        ),
    ]
