# Generated by Django 4.2.17 on 2026-03-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0136_parcelamento_produto_valor'),
        ('produtos', '0024_parcelamento_produto_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelamento',
            options={'ordering': ['marca', 'qtd_vezes'], 'verbose_name': 'Parcelamento', 'verbose_name_plural': 'Parcelamentos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_10_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_12_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_14_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_4_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_6_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_8_vezes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor_repasse_logista',
        ),
        migrations.AlterField(
            model_name='parcelamento',
            name='qtd_vezes',
            field=models.IntegerField(verbose_name='Quantidade de vezes'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Base'),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to='produtos.marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_marca', to='produtos.marca'),
        ),
    ]
