# Generated by Django 4.2.17 on 2026-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_alter_parcelamento_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parcelamento',
            unique_together={('marca', 'qtd_vezes')},
        ),
    ]
