# Generated by Django 4.2.17 on 2026-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0026_parcelamento_unique_marca_qtd_vezes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='entrada_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrada Mínima'),
        ),
    ]
