# Generated by Django 4.2.17 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_entrada_cliente_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='cor',
            field=models.CharField(default='#007bff', help_text='Código HEX ou nome da cor (Ex: #ff0000, primary, etc)', max_length=20),
        ),
        migrations.AddField(
            model_name='marca',
            name='icone',
            field=models.CharField(blank=True, help_text='Classes do ícone (Ex: bx bx-mobile, bi bi-apple)', max_length=50, null=True),
        ),
    ]
