# Generated by Django 4.2.17 on 2026-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_marca_cor_marca_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarcar irá esconder a marca no painel de solicitação.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='icone',
            field=models.CharField(choices=[('bi bi-apple', 'Apple'), ('bx bx-mobile', 'Celular (Padrão/Samsung)'), ('bx bx-mobile-alt', 'Celular 2 (Xiaomi/Outros)'), ('bi bi-phone', 'Celular 3 (Motorola)'), ('bx bx-laptop', 'Notebook / Tablet'), ('bx bx-devices', 'Múltiplos Dispositivos')], default='bx bx-mobile', help_text='Selecione o ícone da marca que aparecerá no sistema', max_length=50),
        ),
    ]
