# Generated by Django 4.2.16 on 2025-07-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_opcaoproduto'),
        ('vendas', '0109_alter_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='opcao_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analise_credito', to='produtos.opcaoproduto', verbose_name='Opção de Preço'),
        ),
    ]
