# Generated by Django 4.2.16 on 2025-09-21 00:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0116_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao_cliente',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='quantidade_dependentes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='recebe_auxilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_renda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
