# Generated by Django 4.2.16 on 2025-09-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0117_cliente_observacao_cliente_cliente_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mais_prazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='sem_contato',
            field=models.BooleanField(default=False),
        ),
    ]
