# Generated by Django 4.2.16 on 2025-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0118_pagamento_mais_prazo_pagamento_sem_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_10',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('4', '4x'), ('6', '6x'), ('8', '8x'), ('10', '10x')], max_length=20),
        ),
    ]
