# Generated by Django 4.2.16 on 2025-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0119_loja_porcentagem_desconto_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='devolucao',
            field=models.BooleanField(default=False),
        ),
    ]
