# Generated by Django 4.2.16 on 2025-11-02 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0120_pagamento_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('cor_hex', models.CharField(default='#6c757d', max_length=7)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='pagamentos', to='vendas.statuspagamento'),
        ),
    ]
