# Generated by Django 4.2.16 on 2025-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0121_statuspagamento_pagamento_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='flag_atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='roubo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='sem_conexao',
            field=models.BooleanField(default=False),
        ),
    ]
