# Generated by Django 4.2.16 on 2025-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0122_pagamento_bo_pagamento_flag_atrasado_pagamento_roubo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='lembrete',
            field=models.BooleanField(default=False),
        ),
    ]
