# Generated by Django 4.2.16 on 2025-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0123_pagamento_lembrete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuspagamento',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, unique=True),
        ),
    ]
