# Generated by Django 4.2.16 on 2025-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0124_alter_statuspagamento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='documento_assinado',
            field=models.FileField(blank=True, null=True, upload_to='documentos_assinados/'),
        ),
        migrations.AddField(
            model_name='venda',
            name='foto_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
    ]
