# Generated by Django 4.2.16 on 2025-11-19 16:23

from django.db import migrations, models
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0125_venda_documento_assinado_venda_foto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='documento_assinado',
            field=models.FileField(blank=True, null=True, upload_to=vendas.models.upload_to_venda),
        ),
        migrations.AlterField(
            model_name='venda',
            name='foto_cliente',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.models.upload_to_venda),
        ),
    ]
