# Generated by Django 4.2.16 on 2026-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0127_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='analise_online',
            field=models.BooleanField(default=False, verbose_name='Análise Online'),
        ),
    ]
