# Generated by Django 4.2.16 on 2026-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0128_analisecreditocliente_analise_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='can_sell_iphones',
            field=models.BooleanField(default=False),
        ),
    ]
