# Generated by Django 4.2.16 on 2026-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0129_loja_can_sell_iphones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='can_sell_iphones',
            new_name='pode_vender_iphone',
        ),
    ]
