# Generated by Django 4.2.16 on 2026-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0130_rename_can_sell_iphones_loja_pode_vender_iphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='email_icloud',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email iCloud'),
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='icloud_configurado_vendedor',
            field=models.BooleanField(default=False, verbose_name='iCloud configurado pelo vendedor'),
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='icloud_confirmado_analista',
            field=models.BooleanField(default=False, verbose_name='iCloud confirmado pelo analista'),
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='senha_icloud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha iCloud'),
        ),
    ]
