# Generated by Django 4.2.16 on 2026-01-27 04:16

from django.db import migrations, models
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0131_analisecreditocliente_email_icloud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='imagem_imei',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.models.upload_to_venda),
        ),
    ]
