# Generated by Django 4.2.16 on 2026-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_produto_is_iphone'),
        ('vendas', '0132_venda_imagem_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='produtos_permitidos',
            field=models.ManyToManyField(blank=True, related_name='lojas_permitidas', to='produtos.produto'),
        ),
    ]
