# Generated by Django 4.2.17 on 2026-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0135_alter_analisecreditocliente_numero_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='entrada_informada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrada informada pelo operador'),
        ),
    ]
