# Generated by Django 4.2.17 on 2026-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0145_observacaosolicitacao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consultaserasaacesso',
            new_name='vendas_cons_cliente_f1f575_idx',
            old_name='vendas_cons_cliente_idx',
        ),
        migrations.AlterField(
            model_name='consultaserasaacesso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observacaosolicitacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
