# Generated by Django 4.2.17 on 2026-05-09 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0031_marca_lojas_permitidas'),
        ('estoque', '0035_remove_estoqueimei_loja_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0147_historicalpagamento_historicalvenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComprovantesCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('modificado_em', models.DateTimeField(blank=True, editable=False)),
                ('documento_identificacao_frente', models.TextField(blank=True, max_length=100, null=True)),
                ('documento_identificacao_frente_analise', models.BooleanField(default=False)),
                ('documento_identificacao_verso', models.TextField(blank=True, max_length=100, null=True)),
                ('documento_identificacao_verso_analise', models.BooleanField(default=False)),
                ('comprovante_residencia', models.TextField(blank=True, max_length=100, null=True)),
                ('comprovante_residencia_analise', models.BooleanField(default=False)),
                ('consulta_serasa', models.TextField(blank=True, max_length=100, null=True)),
                ('consulta_serasa_analise', models.BooleanField(default=False)),
                ('consulta_serasa_2', models.TextField(blank=True, max_length=100, null=True)),
                ('consulta_serasa_2_analise', models.BooleanField(default=False)),
                ('restricao', models.BooleanField(default=False)),
                ('foto_cliente', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comprovantes cliente',
                'verbose_name_plural': 'historical Comprovantes Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAnaliseCreditoCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('modificado_em', models.DateTimeField(blank=True, editable=False)),
                ('data_analise', models.DateTimeField(blank=True, editable=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_reprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EA', 'Em análise'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Cancelado')], default='EA', max_length=20)),
                ('status_aplicativo', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmação pendente'), ('I', 'Instalado')], default='P', max_length=20, verbose_name='Status do aplicativo')),
                ('analise_online', models.BooleanField(default=False, verbose_name='Análise Online')),
                ('data_pagamento', models.CharField(blank=True, choices=[('1', 'Dia 1'), ('10', 'Dia 10'), ('20', 'Dia 20')], max_length=20, null=True, verbose_name='Data de pagamento')),
                ('numero_parcelas', models.CharField(blank=True, max_length=20, null=True)),
                ('imei_informado', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI Informado')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('entrada_informada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrada informada pelo operador')),
                ('email_icloud', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email iCloud')),
                ('senha_icloud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha iCloud')),
                ('icloud_configurado_vendedor', models.BooleanField(default=False, verbose_name='iCloud configurado pelo vendedor')),
                ('icloud_confirmado_analista', models.BooleanField(default=False, verbose_name='iCloud confirmado pelo analista')),
                ('codigo_reserva', models.TextField(blank=True, max_length=100, null=True, verbose_name='Código de Reserva')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprovado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.cliente')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imei', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estoque.estoqueimei')),
                ('loja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('numero_autenticador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.numeroautenticador', verbose_name='Número Autenticador')),
                ('produto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produtos.produto')),
                ('venda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'historical analise credito cliente',
                'verbose_name_plural': 'historical Análises de Crédito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
