# Generated by Django 4.2.17 on 2026-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0150_alter_loja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone_secundario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='telefone_secundario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
