# Generated by Django 4.2.17 on 2026-08-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0151_analisecreditocliente_imei_ultimos_digitos_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAnaliseRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('foto_rg_frente', models.ImageField(upload_to=vendas.models.upload_pre_analise_rapida, verbose_name='Foto do RG (frente)')),
                ('foto_rg_verso', models.ImageField(upload_to=vendas.models.upload_pre_analise_rapida, verbose_name='Foto do RG (costas)')),
                ('tem_comprovante_residencia', models.BooleanField(default=False, verbose_name='Tem comprovante de residência')),
                ('possui_duas_referencias', models.BooleanField(default=False, verbose_name='Possui 2 referências')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Pré-aprovada'), ('R', 'Reprovada')], default='P', max_length=1)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação / motivo')),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_rapidas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('cliente_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_rapidas', to='vendas.cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pré-análise rápida',
                'verbose_name_plural': 'Pré-análises rápidas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
