# Generated by Django 4.2.17 on 2026-08-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0151_analisecreditocliente_imei_ultimos_digitos_vendedor'),
        ('vendas', '0151_cliente_telefone_secundario_and_more'),
    ]

    operations = [
    ]
