# Generated by Django 4.2.17 on 2026-08-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0152_merge_20260803_1919'),
        ('vendas', '0152_preanaliserapida'),
    ]

    operations = [
    ]
