# Generated by Django 4.2.17 on 2026-08-27 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0153_merge_0152_merge_20260803_1919_0152_preanaliserapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='preanaliserapida',
            name='consulta_serasa',
            field=models.FileField(blank=True, null=True, upload_to=vendas.models.upload_pre_analise_rapida, verbose_name='Consulta Serasa'),
        ),
        migrations.AddField(
            model_name='preanaliserapida',
            name='consulta_serasa_anexada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preanaliserapida',
            name='consulta_serasa_anexada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_analises_rapidas_serasa', to=settings.AUTH_USER_MODEL),
        ),
    ]
