# Generated by Django 4.2.17 on 2026-09-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0154_preanaliserapida_consulta_serasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preanaliserapida',
            name='segunda_compra',
            field=models.BooleanField(default=False, verbose_name='É a segunda compra do cliente conosco'),
        ),
    ]
