# Generated by Django 4.2.17 on 2026-09-22 22:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0155_preanaliserapida_segunda_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to=vendas.models.upload_to_comprovante_parcela, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic'])], verbose_name='Arquivo do comprovante')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='vendas.parcela')),
            ],
            options={
                'verbose_name': 'Comprovante de Parcela',
                'verbose_name_plural': 'Comprovantes de Parcelas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
