# Generated by Django 4.2.16 on 2026-07-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0024_alter_caixamensal_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repasse',
            options={
                'ordering': ['-data'],
                'permissions': [('add_notificacaobo', 'Pode gerar notificação BO')],
                'verbose_name': 'Repasse',
                'verbose_name_plural': 'Repasse',
            },
        ),
    ]