# Generated by Django 4.2.17 on 2026-07-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_alter_repasse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repasse',
            options={'ordering': ['-data'], 'permissions': (('add_notificacaobo', 'Pode gerar notificação BO'),), 'verbose_name': 'Repasse', 'verbose_name_plural': 'Repasse'},
        ),
    ]
